[package]
name = "pulsar-rs"
version = "0.1.0"
authors = ["Chris Day <christopher_day@eogresources.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.51.1"

